### ISSUE TITLE
Devtools 1.7.0 on MacOS 11.6.4 shows a blank window

### ISSUE THREAD

**Issue by sangupta** [fosslife/devtools-x#22]
The "about" menu works to display application logo and version but rest of application remains blank.

**Comment by plasticle** [comment]
looks like it is caused by CSP issues.

Same problem on Macos 12.6, errors in console:

```[Error] Refused to load tauri://localhost/src/vips/vips.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load tauri://localhost/assets/index.76129d8a.js because it does not appear in the script-src directive of the Content Security Policy.```

**Comment by r0skar** [comment]
Same thing is happening on Linux using either the AppImage or deb file. No "about" menu visible - just a blank white window. Tested it with v1.7 as well as 1.6 - both result in a white window.

```bash
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.9-arch1-1 (64-bit)
Graphics Platform: Wayland
```

**Comment by acketon** [comment]
Same here on MacOS 12.4 on an M1

**Comment by neilsh** [comment]
Looking at the issue at https://github.com/tauri-apps/tauri/issues/3583 , I think a `script-src:` entry might need to be added here: https://github.com/fosslife/devtools-x/blob/fa49008d239a115b53ef9337d1dfb81e21393da5/src-tauri/tauri.conf.json#L56-L60

**Comment by nickybu** [comment]
Same here on macOS v11.5.2

**Comment by aemadrid-twx** [comment]
same on macOS 12.6 arm

**Comment by cocoonkid** [comment]
Same here, but keep up the great job! looking forward to it working!

**Comment by raulfdm** [comment]
yes

**Comment by NderimPlanA** [comment]
Same here. MacOS Monterey 2020 M1.

**Comment by Sparkenstein** [comment]
Apologies for delayed reply. yes this was an issue with CSP, which I have removed completely (the image compressor module)
I have also tested the application on Mac, windows and Linux (wsl) now. please try latest release v1.7.1 and let me know if the issue still persists.

The image module will be rewritten and will be reintroduced in upcoming versions

**Comment by jackphilippi** [comment]
@Sparkenstein thanks for your quick work on this. That issue seems to have subsided, but I'm seeing another error still:

I'm using a M1 Macbook v11.5.2 and I can build/run the app using `yarn start`, however i'm greeted with a white screen and the following error. Happy to assist in debugging if you need. I can't see at a glance from the code why we would be seeing that issue

**Comment by mo-fippi** [comment]
@Sparkenstein thanks for your quick work on this. That issue seems to have subsided, but I'm seeing another error still:

I'm using a Gen 1 M1 Macbook and I can build/run the app using `yarn start`, however i'm greeted with a white screen and the following error. Happy to assist in debugging if you need. 

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/82349662/191412060-9f7b75c4-e122-4644-8e6e-05cde61efd4c.png">

**Comment by jackphilippi** [comment]
> @Sparkenstein thanks for your quick work on this. That issue seems to have subsided, but I'm seeing another error still:
> 
> I'm using a M1 Macbook v11.5.2 and I can build/run the app using `yarn start`, however i'm greeted with a white screen and the following error. Happy to assist in debugging if you need. I can't see at a glance from the code why we would be seeing that issue
> 
> <..image>

To extend on this, I can see the issue seems to be coming from the import in `src/utils/db.ts`. If I comment out the `db.ts` file and mock it with something like the following, the app runs for me OK, but just lacks config functionality. I don't understand how tauri-apps works enough to be able to get much further

```typescript
const db = {
  data: {
    theme: "dark",
    pinned: [],
    jsoneditor: { tabsstate: {} },
    hashes: {},
  },
  read: function () {
    console.log("read() called.");
    return this.data;
  },
  write: function () {
    console.log("write() called.");
  },
};
```

**Comment by cocoonkid** [comment]
Can confirm. Works now. Thanks for the quick fix!

**Comment by cocoonkid** [comment]
In "Number Tools" as soon as I change the number ( I want 64) it blanks out.

```
Error: Second augument must be between 2 and 62.
```
